.\" To view this, try `groff -Tascii -mdoc cron.1 | less -R`
.Dt CRON 1
.Sh NAME
.Nm cron
.Nd utility printing the number of seconds matching cron expressions.
.Sh SYNOPSIS
.Nm
.Op Ar options
.Sh OPTIONS
if optionts are absent, it prints the number of seconds to next minute.
.Bl -tag -width Ds
.It Fl \-minute Ar minute
set the cron expression field for minute.
.It Fl \-hour Ar hour
set the cron expression field for hour.
.It Fl m Ar minute
same as
.Fl \-minute
.It Fl h Ar hour
same as
.Fl \-hour
.El
.Sh EXAMPLES
To use this in a shell script loop, consider to the following example:
.Bd -literal -offset indent
#!/bin/sh

while true; do
   sleep `cron --hour X --minute Y`
   echo "Current time is `date`."

   # Your job.
done
.Ed
.Sh DOCKER
See dockerfiels folder for usages or use
.Em xiejw/cron
directly.
