#!/bin/sh

# vim: filetype=sh

set -x

CC=/usr/bin/clang
CXX=/usr/bin/clang++

mkdir -p dependencies
cd dependencies

if [ ! -d "gflags" ]; then
  # https://github.com/gflags/gflags/blob/master/INSTALL.md
  git clone https://github.com/gflags/gflags.git
  cd gflags
  mkdir buildlib
  cd buildlib
  cmake ..
  make
  cd ..
  cd ..
else
  echo "Skip gflags."
fi

if [ ! -d "googletest" ]; then
  # https://github.com/google/googletest
  git clone https://github.com/google/googletest
  cd googletest
  mkdir buildlib
  cd buildlib
  cmake ..
  make
  cd ..
  cd ..
else
  echo "Skip googletest."
fi
