.TH CRON 1
.SH NAME
cron \- utility printing the number of seconds matching cron expressions.
.SH SYNOPSIS
.B cron
[options]
.SH OPTIONS
.PP
if optionts are absent, it prints the number of seconds to next minute.
.TP
.BR \-m ", " \-\-minute-\fIminute\fR
set the cron expression field for minute.
.TP
.BR \-h ", " \-\-hour=\fIhour\fR
set the cron expression field for hour.
